// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCxgeqIZ1KxKdCTa2RQExK9LZMjBbD4XIU',
    appId: '1:1042065447563:web:5290327a1fd95bca0f128e',
    messagingSenderId: '1042065447563',
    projectId: 'demotp-46f3d',
    authDomain: 'demotp-46f3d.firebaseapp.com',
    storageBucket: 'demotp-46f3d.firebasestorage.app',
    measurementId: 'G-C5C11V6P69',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDzQqnEB76AksRO5GpBwOZIOMQRiQhBW_Y',
    appId: '1:1042065447563:android:6d5bd8deb7acc1d00f128e',
    messagingSenderId: '1042065447563',
    projectId: 'demotp-46f3d',
    storageBucket: 'demotp-46f3d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCe4Hlxa8lS_o8DqFOqlnSZ-oZF-mJH128',
    appId: '1:1042065447563:ios:acbd792686730bd70f128e',
    messagingSenderId: '1042065447563',
    projectId: 'demotp-46f3d',
    storageBucket: 'demotp-46f3d.firebasestorage.app',
    iosBundleId: 'com.example.attendance',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCe4Hlxa8lS_o8DqFOqlnSZ-oZF-mJH128',
    appId: '1:1042065447563:ios:acbd792686730bd70f128e',
    messagingSenderId: '1042065447563',
    projectId: 'demotp-46f3d',
    storageBucket: 'demotp-46f3d.firebasestorage.app',
    iosBundleId: 'com.example.attendance',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCxgeqIZ1KxKdCTa2RQExK9LZMjBbD4XIU',
    appId: '1:1042065447563:web:19c3601613a19f260f128e',
    messagingSenderId: '1042065447563',
    projectId: 'demotp-46f3d',
    authDomain: 'demotp-46f3d.firebaseapp.com',
    storageBucket: 'demotp-46f3d.firebasestorage.app',
    measurementId: 'G-YV5KV90ND0',
  );
}
